export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const CREATE_POST = "CREATE_POST";
export const FETCH_POST_FAILED = "FETCH_POST_FAILED";
export const CLEAR_POST_STATE = "CLEAR_POST_STATE";

export const FETCH_SINGLE_POST = "FETCH_SINGLE_POST";
export const FETCH_SINGLE_START = "FETCH_SINGLE_START";
export const FETCH_SINGLE_FAILED = "FETCH_SINGLE_FAILED";

export const LIKE_POST = "LIKE_POST";

export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGOUT = "LOGOUT";

export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";

export const FETCH_START = "FETCH_START";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_FRIENDS_OF_USER = "FETCH_FRIENDS_OF_USER";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
