export const UPDATE_POSTS = 'UPDATE_POSTS';
export const CREATE_POST = "CREATE_POST";
export const FETCH_POST_FAILED = "FETCH_POST_FAILED";
export const CLEAR_POST_STATE = "CLEAR_POST_STATE";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGOUT = "LOGOUT";

export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";